### ISSUE TITLE
Revamp

### ISSUE THREAD

**Issue by rob-luke** [JuliaNeuro/ROADMAP#3]
@alexmorley I think you have moved on from this work? Any chance you could give me the full admin rights to the organisation, I would like to move a bunch of work under a single umbrella.

**Comment by alexmorley** [comment]
sorry totally missed this. sure thing.

**Comment by rob-luke** [comment]
Thanks @alexmorley, I'll do a revamp of the settings etc. Please feel free to comment etc, but I won't wait for feedback to merge changes etc unless you say so.
